{% set name = "openff-bespokefit" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/openforcefield/openff-bespokefit/archive/refs/tags/{{ version }}.tar.gz
  sha256: 91b018997e6ec8eaf32d5f9f1fd9ab387e870561653c3a834c4c280411683e1f

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - numpy
    - pydantic
    - pyyaml
    - tqdm
    - rich
    - click >=8.0.0
    - click-option-group
    - rdkit
    - openff-utilities
    - openff-toolkit-base >=0.10.0,<0.11.0a0
    - openff-forcefields
    - openff-qcsubmit
    - forcebalance >=1.9.2
    - openff-fragmenter-base >=0.1.2
    - openmm >=7.6.0
    - qcportal >=0.15.6
    - qcengine >=0.23.0
    - qcelemental >=0.24.0
    - chemper
    - geometric
    - torsiondrive
    - uvicorn
    - fastapi
    - celery >=5.0.0
    - httpx
    - redis-server
    - redis-py
    # https://github.com/openforcefield/openff-bespokefit/issues/162#issuecomment-1108840723
    - h5py <3.2

test:
  imports:
    - openff.bespokefit

about:
  home: https://openforcefield.org/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Automated tools for the generation of bespoke SMIRNOFF format parameters for individual molecules.
  dev_url: https://github.com/openforcefield/openff-bespokefit

extra:
  recipe-maintainers:
    - j-wags
    - mattwthompson
    - jthorton
    - SimonBoothroyd
    - Yoshanuikabundi 
