{% set name = "openff-bespokefit" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/openforcefield/openff-bespokefit/archive/refs/tags/{{ version }}.tar.gz
  sha256: 29275bd86dfe553fa3e4566be93c775ab7752a32f1643f596863a0698a93921e

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - numpy
    - pydantic
    - pyyaml
    - tqdm
    - rich
    - click >=8.0.0
    - click-option-group
    - rdkit
    - openff-utilities
    - openff-toolkit-base >=0.11
    - openff-forcefields
    - openff-qcsubmit
    - forcebalance
    - openff-fragmenter-base
    - openmm
    - qcportal >=0.15.6
    - qcengine >=0.25
    - qcelemental >=0.24.0
    - chemper
    - geometric
    - torsiondrive
    - uvicorn
    - fastapi
    - celery >=5.0.0
    - httpx
    - redis-server
    - redis-py
    # https://github.com/openforcefield/openff-bespokefit/issues/162#issuecomment-1108840723
    - h5py <3.2
  run_constrained:
    - starlette =0.20
    - importlib_metadata >=4
    - importlib-metadata >=4

test:
  imports:
    - openff.bespokefit

about:
  home: https://openforcefield.org/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Automated tools for the generation of bespoke SMIRNOFF format parameters for individual molecules.
  dev_url: https://github.com/openforcefield/openff-bespokefit

extra:
  recipe-maintainers:
    - j-wags
    - mattwthompson
    - jthorton
    - SimonBoothroyd
    - Yoshanuikabundi 
